### ISSUE TITLE
日本語翻訳 Tracking Issue

### ISSUE THREAD

**Issue by t-hamano** [jawordpressorg/developer-plugins-handbook#1]
このissueは、プラグイン開発者ハンドブックの日本語化にあたり、原文の対象ページをリストアップし、各ページの進捗を管理するものです。

注：プラグインハンドブックの日本語訳は、これまで別リポジトリ（[plugin-handbook](https://github.com/jawordpressorg/plugin-handbook)）で管理されていましたが、[原文のGitHub化](https://github.com/WordPress/developer-plugins-handbook)にともない、それをフォークした当リポジトリで管理することになりました。旧リポジトリで翻訳済のページについては、この一覧にも反映済です。

## ✅ Index

- [x] [Index](https://developer.wordpress.org/plugins/) https://github.com/jawordpressorg/plugin-handbook/pull/14

## ✅ Introduction to Plugin Development

- [x] [Introduction to Plugin Development](https://developer.wordpress.org/plugins/intro/) https://github.com/jawordpressorg/plugin-handbook/pull/4
- [x] [Introduction to Plugin Development > What is a Plugin?](https://developer.wordpress.org/plugins/intro/what-is-a-plugin/) https://github.com/jawordpressorg/plugin-handbook/pull/6

## ✅ Plugin Basics

- [x] [Plugin Basics](https://developer.wordpress.org/plugins/plugin-basics/) https://github.com/jawordpressorg/plugin-handbook/pull/21
- [x] [Plugin Basics > Header Requirements](https://developer.wordpress.org/plugins/plugin-basics/header-requirements/) #62
- [x] [Plugin Basics > Activation / Deactivation Hooks](https://developer.wordpress.org/plugins/plugin-basics/activation-deactivation-hooks/) #65
- [x] [Plugin Basics > Best Practices](https://developer.wordpress.org/plugins/plugin-basics/best-practices/) #51
- [x] [Plugin Basics > Determining Plugin and Content Directories](https://developer.wordpress.org/plugins/plugin-basics/determining-plugin-and-content-directories/) #61
- [x] [Plugin Basics > Including a Software License](https://developer.wordpress.org/plugins/plugin-basics/including-a-software-license/) #63
- [x] [Plugin Basics > Uninstall Methods](https://developer.wordpress.org/plugins/plugin-basics/uninstall-methods/) #64

## ✅ Plugin Security

- [x] [Plugin Security](https://developer.wordpress.org/plugins/security/) https://github.com/jawordpressorg/plugin-handbook/pull/30
- [x] [Plugin Security > Checking User Capabilities](https://developer.wordpress.org/plugins/security/checking-user-capabilities/) #130
- [x] [Plugin Security > Data Validation](https://developer.wordpress.org/plugins/security/data-validation/) #122
- [x] [Plugin Security > Nonces](https://developer.wordpress.org/plugins/security/nonces/) #124
- [x] [Plugin Security > Securing (escaping) Output](https://developer.wordpress.org/plugins/security/securing-output/) #128
- [x] [Plugin Security > Securing (sanitizing) Input](https://developer.wordpress.org/plugins/security/securing-input/) #126

## ✅ Hooks

- [x] [Hooks](https://developer.wordpress.org/plugins/hooks/) #67
- [x] [Hooks > Actions](https://developer.wordpress.org/plugins/hooks/actions/) #69 
- [x] [Hooks > Advanced Topics](https://developer.wordpress.org/plugins/hooks/advanced-topics/) #75
- [x] [Hooks > Custom Hooks](https://developer.wordpress.org/plugins/hooks/custom-hooks/) #73
- [x] [Hooks > Filters](https://developer.wordpress.org/plugins/hooks/filters/) #71

## ✅ Privacy

- [x] [Privacy](https://developer.wordpress.org/plugins/privacy/) #110
- [x] [Privacy > Adding the Personal Data Eraser to Your Plugin](https://developer.wordpress.org/plugins/privacy/adding-the-personal-data-eraser-to-your-plugin/) #106
- [x] [Privacy > Adding the Personal Data Exporter to Your Plugin](https://developer.wordpress.org/plugins/privacy/adding-the-personal-data-exporter-to-your-plugin/) #104
- [x] [Privacy > Privacy Related Options, Hooks and Capabilities](https://developer.wordpress.org/plugins/privacy/privacy-related-options-hooks-and-capabilities/) #102
- [x] [Privacy > Suggesting text for the site privacy policy](https://developer.wordpress.org/plugins/privacy/suggesting-text-for-the-site-privacy-policy/) #108

## ✅ Administration Menus

- [x] [Administration Menus](https://developer.wordpress.org/plugins/administration-menus/) https://github.com/jawordpressorg/plugin-handbook/pull/24
- [x] [Administration Menus > Sub-Menus](https://developer.wordpress.org/plugins/administration-menus/sub-menus/) #7
- [x] [Administration Menus > Top-Level Menus](https://developer.wordpress.org/plugins/administration-menus/top-level-menus/) #7

## ✅ Shortcodes

- [x] [Shortcodes](https://developer.wordpress.org/plugins/shortcodes/) #84
- [x] [Shortcodes > Basic Shortcodes](https://developer.wordpress.org/plugins/shortcodes/basic-shortcodes/) #86
- [x] [Shortcodes > Enclosing Shortcodes](https://developer.wordpress.org/plugins/shortcodes/enclosing-shortcodes/) #88
- [x] [Shortcodes > Shortcodes with Parameters](https://developer.wordpress.org/plugins/shortcodes/shortcodes-with-parameters/) #90
- [x] [Shortcodes > TinyMCE Enhanced Shortcodes](https://developer.wordpress.org/plugins/shortcodes/tinymce-enhanced-shortcodes/) #92

## ✅ Settings

- [x] [Settings](https://developer.wordpress.org/plugins/settings/) https://github.com/jawordpressorg/plugin-handbook/pull/28
- [x] [Settings > Custom Settings Page](https://developer.wordpress.org/plugins/settings/custom-settings-page/) #98
- [x] [Settings > Options API](https://developer.wordpress.org/plugins/settings/options-api/) #96
- [x] [Settings > Settings API](https://developer.wordpress.org/plugins/settings/settings-api/) #94
- [x] [Settings > Using Settings API](https://developer.wordpress.org/plugins/settings/using-settings-api/) #100

## ✅ Metadata

- [x] [Metadata](https://developer.wordpress.org/plugins/metadata/) https://github.com/jawordpressorg/plugin-handbook/pull/34
- [x] [Metadata > Managing Post Metadata](https://developer.wordpress.org/plugins/metadata/managing-post-metadata/) #78
- [x] [Metadata > Custom Meta Boxes](https://developer.wordpress.org/plugins/metadata/custom-meta-boxes/) #82
- [x] [Metadata > Rendering Post Metadata](https://developer.wordpress.org/plugins/metadata/rendering-post-metadata/) #80

## ✅ Custom Post Types

- [x] [Custom Post Types](https://developer.wordpress.org/plugins/post-types/) https://github.com/jawordpressorg/plugin-handbook/pull/26
- [x] [Custom Post Types > Registering Custom Post Types](https://developer.wordpress.org/plugins/post-types/registering-custom-post-types/) #47
- [x] [Custom Post Types > Working with Custom Post Types](https://developer.wordpress.org/plugins/post-types/working-with-custom-post-types/) #49

## ✅ Taxonomies

- [x] [Taxonomies](https://developer.wordpress.org/plugins/taxonomies/) https://github.com/jawordpressorg/plugin-handbook/pull/36
- [x] [Taxonomies > Term Splitting (WordPress 4.2)](https://developer.wordpress.org/plugins/taxonomies/split-terms-wp-4-2/) #41
- [x] [Taxonomies > Working with Custom Taxonomies](https://developer.wordpress.org/plugins/taxonomies/working-with-custom-taxonomies/) #39

## ✅ Users

- [x] [Users](https://developer.wordpress.org/plugins/users/) #35 
- [x] [Users > Roles and Capabilities](https://developer.wordpress.org/plugins/users/roles-and-capabilities/) #31
- [x] [Users > Working with User Metadata](https://developer.wordpress.org/plugins/users/working-with-user-metadata/) #33
- [x] [Users > Working with Users](https://developer.wordpress.org/plugins/users/working-with-users/) #37 
- [x] [Users > HTTP API](https://developer.wordpress.org/plugins/http-api/) #29

## ✅ JavaScript

- [x] [JavaScript](https://developer.wordpress.org/plugins/javascript/) https://github.com/jawordpressorg/plugin-handbook/pull/32
- [x] [JavaScript > Heartbeat API](https://developer.wordpress.org/plugins/javascript/heartbeat-api/) #7
- [x] [JavaScript > jQuery](https://developer.wordpress.org/plugins/javascript/jquery/) #7
- [x] [JavaScript > AJAX](https://developer.wordpress.org/plugins/javascript/ajax/) #28
- [x] [JavaScript > Server Side PHP and Enqueuing](https://developer.wordpress.org/plugins/javascript/enqueuing/) #27
- [x] [JavaScript > Summary](https://developer.wordpress.org/plugins/javascript/summary/) #7

## ✅ Cron

- [x] [Cron](https://developer.wordpress.org/plugins/cron/) #112
- [x] [Cron > Hooking WP-Cron Into the System Task Scheduler](https://developer.wordpress.org/plugins/cron/hooking-wp-cron-into-the-system-task-scheduler/) #118
- [x] [Cron > Scheduling WP Cron Events](https://developer.wordpress.org/plugins/cron/scheduling-wp-cron-events/) #116
- [x] [Cron > Testing of WP-Cron](https://developer.wordpress.org/plugins/cron/simple-testing/) #120
- [x] [Cron > Understanding WP-Cron Scheduling](https://developer.wordpress.org/plugins/cron/understanding-wp-cron-scheduling/) #114

## ✅ Internationalization

- [x] [Internationalization](https://developer.wordpress.org/plugins/internationalization/) #7
- [x] [Internationalization > How to Internationalize Your Plugin](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/) #7
- [x] [Internationalization > Internationalization Security](https://developer.wordpress.org/plugins/internationalization/security/) #7
- [x] [Internationalization > Localization](https://developer.wordpress.org/plugins/internationalization/localization/) #7

## The WordPress.org Plugin Directory

- [x] [The WordPress.org Plugin Directory](https://developer.wordpress.org/plugins/wordpress-org/) #132
- [ ] [The WordPress.org Plugin Directory > Add Your Plugin to the Block Directory](https://developer.wordpress.org/plugins/wordpress-org/add-your-plugin-to-the-block-directory/)
- [x] [The WordPress.org Plugin Directory > Alerts and Warnings](https://developer.wordpress.org/plugins/wordpress-org/alerts-and-warnings/) #134
- [ ] [The WordPress.org Plugin Directory > Block Specific Plugin Guidelines](https://developer.wordpress.org/plugins/wordpress-org/block-specific-plugin-guidelines/)
- [ ] [The WordPress.org Plugin Directory > Compliance Disclaimers](https://developer.wordpress.org/plugins/wordpress-org/compliance-disclaimers/)
- [x] [The WordPress.org Plugin Directory > Detailed Plugin Guidelines](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/) #144
- [x] [The WordPress.org Plugin Directory > How Your Plugin Assets Work](https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/) #7
- [x] [The WordPress.org Plugin Directory > Managing Your Plugin’s Security](https://developer.wordpress.org/plugins/wordpress-org/plugin-security/) #138
- [ ] [The WordPress.org Plugin Directory > Managing Your Plugin’s Security > Reporting Plugin Security Issues](https://developer.wordpress.org/plugins/wordpress-org/plugin-security/reporting-plugin-security-issues/)
- [x] [The WordPress.org Plugin Directory > Planning, Submitting, and Maintaining Plugins](https://developer.wordpress.org/plugins/wordpress-org/planning-submitting-and-maintaining-plugins/) #136
- [x] [The WordPress.org Plugin Directory > Plugin Developer FAQ](https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/)
  - #146
  - #148
  - #150
  - #152
  - #154
  - #156
  - #158
  - #160
  - #164
- [ ] [The WordPress.org Plugin Directory > Plugin Readmes](https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/)
- [ ] [The WordPress.org Plugin Directory > Preventing WordPress from Updating Your External Plugin](https://developer.wordpress.org/plugins/wordpress-org/preventing-wordpress-from-updating-your-external-plugin/)
- [x] [The WordPress.org Plugin Directory > Previews and Blueprints](https://developer.wordpress.org/plugins/wordpress-org/previews-and-blueprints/) #140
- [ ] [The WordPress.org Plugin Directory > Release Confirmation Emails](https://developer.wordpress.org/plugins/wordpress-org/release-confirmation-emails/)
- [ ] [The WordPress.org Plugin Directory > Special User Roles and Capabilities](https://developer.wordpress.org/plugins/wordpress-org/special-user-roles-capabilities/)
- [ ] [The WordPress.org Plugin Directory > Take Over an Existing Plugin](https://developer.wordpress.org/plugins/wordpress-org/take-over-an-existing-plugin/)
- [ ] [The WordPress.org Plugin Directory > Transferring Your Plugin to a New Owner](https://developer.wordpress.org/plugins/wordpress-org/transferring-your-plugin-to-a-new-owner/)
- [x] [The WordPress.org Plugin Directory > Using Subversion](https://developer.wordpress.org/plugins/wordpress-org/how-to-use-subversion/) #142
- [ ] [The WordPress.org Plugin Directory > Using the Forums](https://developer.wordpress.org/plugins/wordpress-org/using-the-forums/)
- [x] [Developer Tools](https://developer.wordpress.org/plugins/developer-tools/) https://github.com/jawordpressorg/plugin-handbook/pull/18

## ✅ Developer Tools

- [x] [Developer Tools > Debug Bar and Add-Ons](https://developer.wordpress.org/plugins/developer-tools/debug-bar-and-add-ons/) #45
- [x] [Developer Tools > Helper Plugins](https://developer.wordpress.org/plugins/developer-tools/helper-plugins/) #43 #76

## Others

- [x] [Credits](https://developer.wordpress.org/plugins/credits/) https://github.com/jawordpressorg/plugin-handbook/pull/2
- [ ] [Controller Classes](https://developer.wordpress.org/plugins/controller-classes/)
- [ ] [Requests](https://developer.wordpress.org/plugins/requests/)
- [ ] [Responses](https://developer.wordpress.org/plugins/responses-2/)
- [ ] [REST API](https://developer.wordpress.org/plugins/rest-api/)
- [ ] [REST API Overview](https://developer.wordpress.org/plugins/rest-api-overview/)
- [ ] [Routes & Endpoints](https://developer.wordpress.org/plugins/routes-endpoints/)
- [ ] [Schema](https://developer.wordpress.org/plugins/schema/)

**Comment by t-hamano** [comment]
https://github.com/jawordpressorg/developer-plugins-handbook/commit/4dd6fc27e7cfee6c371ff23ceb91233f556e54e9 で、日本語版リポジトリをアップストリームとして同期しました。日本語リポジトリは既にすべてのページが翻訳済ですが、同期によって生じた差分は新しく #185 で管理する事にするため、このissueはクローズします。
