### ISSUE TITLE
日本語翻訳 Tracking Issue （2024/09/21同期後）

### ISSUE THREAD

**Issue by t-hamano** [jawordpressorg/developer-plugins-handbook#185]
#1 のフォローアップ

4dd6fc2 で、日本語版リポジトリをアップストリームとして同期しました。
このTracking Issueでは、同期によって発生した追加ページ・差分を翻訳する事を目的としています。

## 更新されたファイル

- [x] [Hooks > Actions](https://developer.wordpress.org/plugins/hooks/actions/): 差分は生じているが、原文に変更なし。
- [x] [Plugin Basics > Best Practices](https://developer.wordpress.org/plugins/plugin-basics/best-practices/): 一文字のみの変更のため、同期時に修正済。
- [x] [Privacy > Adding the Personal Data Eraser to Your Plugin](https://developer.wordpress.org/plugins/privacy/adding-the-personal-data-eraser-to-your-plugin/): 差分は生じているが、原文に変更なし。
- [x] [Users > Working with User Metadata](https://developer.wordpress.org/plugins/users/working-with-user-metadata/): 差分は生じているが、同期にの誤りのため、[#186](https://github.com/jawordpressorg/developer-plugins-handbook/pull/186) にて修正済。
- [x] [The WordPress.org Plugin Directory](https://developer.wordpress.org/plugins/wordpress-org/): 原文に一文の追加あり。
  - #191
- [x] [The WordPress.org Plugin Directory > Using Subversion](https://developer.wordpress.org/plugins/wordpress-org/how-to-use-subversion/): リスト項目の削除と一つの単語がコードタグで囲まれただけなので、同期時に修正済。
- [x] [The WordPress.org Plugin Directory > Plugin Developer FAQ](https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/): 段落から見出しへの変更あり。軽微なため同期時に修正済。

## 新規追加されたファイル

- [x] [REST API](https://developer.wordpress.org/plugins/rest-api/) #189 
- [x] [REST API > REST API Overview](https://developer.wordpress.org/plugins/rest-api/rest-api-overview/) #193 
- [x] [REST API > Routes & Endpoints](https://developer.wordpress.org/plugins/rest-api/routes-endpoints/) #195
- [x] [REST API > Requests](https://developer.wordpress.org/plugins/rest-api/requests/) #197 
- [x] [REST API > Responses](https://developer.wordpress.org/plugins/rest-api/responses-2/) #203
- [x] [REST API > Controller Classes](https://developer.wordpress.org/plugins/rest-api/controller-classes/) #199 
- [x] [REST API > Schema](https://developer.wordpress.org/plugins/rest-api/schema/) #201 
- [x] [The WordPress.org Plugin Directory](https://developer.wordpress.org/plugins/wordpress-org/) #191 
- [x] [The WordPress.org Plugin Directory > Add Your Plugin to the Block Directory](https://developer.wordpress.org/plugins/wordpress-org/add-your-plugin-to-the-block-directory/) #213 
- [x] [The WordPress.org Plugin Directory > Block Specific Plugin Guidelines](https://developer.wordpress.org/plugins/wordpress-org/block-specific-plugin-guidelines/) #321
- [x] [The WordPress.org Plugin Directory > Common issues](https://developer.wordpress.org/plugins/wordpress-org/common-issues/) #323
- [x] [The WordPress.org Plugin Directory > Compliance Disclaimers](https://developer.wordpress.org/plugins/wordpress-org/compliance-disclaimers/) #217
- [x] [The WordPress.org Plugin Directory > Managing Your Plugin’s Security > Reporting Plugin Security Issues](https://developer.wordpress.org/plugins/wordpress-org/plugin-security/reporting-plugin-security-issues/)  #211 
- [x] [The WordPress.org Plugin Directory > Plugin Readmes](https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/) #317
- [x] [The WordPress.org Plugin Directory > Preventing WordPress from Updating Your External Plugin](https://developer.wordpress.org/plugins/wordpress-org/preventing-wordpress-from-updating-your-external-plugin/) #215 
- [x] [The WordPress.org Plugin Directory > Release Confirmation Emails](https://developer.wordpress.org/plugins/wordpress-org/release-confirmation-emails/) #209 
- [x] [The WordPress.org Plugin Directory > Special User Roles and Capabilities](https://developer.wordpress.org/plugins/wordpress-org/special-user-roles-capabilities/) #207 
- [x] [The WordPress.org Plugin Directory > Take Over an Existing Plugin](https://developer.wordpress.org/plugins/wordpress-org/take-over-an-existing-plugin/) #319
- [x] [The WordPress.org Plugin Directory > Transferring Your Plugin to a New Owner](https://developer.wordpress.org/plugins/wordpress-org/transferring-your-plugin-to-a-new-owner/) #205 
- [x] [The WordPress.org Plugin Directory > Using the Forums](https://developer.wordpress.org/plugins/wordpress-org/using-the-forums/) #219

## その他

以下は同期時に生じた差分ではありませんが、チェック時に気づいた対応が必要そうなものです。

- [ ] [The WordPress.org Plugin Directory > Previews and Blueprints](https://developer.wordpress.org/plugins/wordpress-org/previews-and-blueprints/): `img` 要素の `alt`属性が英語のため、img 要素自体をコメントアウトして翻訳する必要あり。（[ソース](https://github.com/jawordpressorg/developer-plugins-handbook/blob/c0e43d0ad74716fb1328cd44f7b33602cdf6cd54/wordpress-org/previews-and-blueprints/index.md#L53)）

**Comment by t-hamano** [comment]
再度原文との同期を行い、新しい #372 を立てたので、当issueはクローズします。
